# Supabase CLI configuration
project_ref = "wqqgwajlfyevlkunfpdt"
api_key = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndxcWd3YWpsZnlldmxrdW5mcGR0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjE5MDI2NzQsImV4cCI6MjA3NzQ3ODY3NH0.d3WxQVuhmRYV6yAsEyy8rj4J06SF3ELnrXMsXjkUI9k"
